bhagsahan/models/recipes.py
import mongoengine as me
import datetime


class Ingredient(me.EmbeddedDocument):
    name = me.StringField()
    volume = me.IntField()
    amount_type = me.StringField()


class Recipe(me.Document):
    meta = {'collection': 'recipes'}

    name = me.StringField(required=True)
    description = me.StringField()
    tags = me.ListField(me.StringField())

    ingredients = me.ListField(me.EmbeddedDocumentField(Ingredient))
    methods = me.ListField(me.StringField())
    unit = me.StringField()
    calories = me.IntField(required=True, default=0)

    image = me.FileField()
    
    status = me.BooleanField(required=False, default=False)
    ingredient_status = me.BooleanField(required=False, default=False)
    allergen_status = me.BooleanField(required=False, default=False)
    side_dish = me.BooleanField(required=False, default=False)

    created_date = me.DateTimeField(required=True,
                                    default=datetime.datetime.utcnow)
    update_date = me.DateTimeField(required=True,
                                   default=datetime.datetime.utcnow)

bhagsahan/forms/recipe.py
from flask_wtf import FlaskForm
from wtforms import fields, Form
from wtforms import validators


class IngredientForm(Form):
    in_name = fields.TextField('Name',
                            validators=[validators.InputRequired()])
    volume = fields.IntegerField('Volume')
    amount_type = fields.TextField('Amount Type')


class MethodForm(Form):
    info = fields.TextField('Method',
                            validators=[validators.InputRequired()])


class RecipeForm(FlaskForm):
    name = fields.TextField('Name',
                             validators=[validators.InputRequired()])
    description = fields.TextField('Description')
    tags = fields.TextField('Tags')
    unit = fields.TextField('Unit')
    calories = fields.IntegerField('Calories',
                               validators=[validators.InputRequired()])

    ingredient_num = fields.SelectField('Number of ingredient',
                                            choices=[(1, '1'),
                                                        (2, '2'),
                                                        (3, '3'),
                                                        (4, '4'),
                                                        (5, '5'),
                                                        (6, '6'),
                                                        (7, '7'),
                                                        (8, '8'),
                                                        (9, '9'),
                                                        (10, '10')],
                                            coerce=int)
    methods_num = fields.SelectField('Number of method',
                                            choices=[(1, '1'),
                                                        (2, '2'),
                                                        (3, '3'),
                                                        (4, '4'),
                                                        (5, '5'),
                                                        (6, '6'),
                                                        (7, '7'),
                                                        (8, '8'),
                                                        (9, '9'),
                                                        (10, '10')],
                                            coerce=int)
    
    food_type = fields.SelectField('Number of method',
                                            choices=[('A la carte', 'A la carte'),
                                                     ('Side dish', 'Side dish'),
                                                    ])


class ListForm(FlaskForm):
    ingredients = fields.FieldList(fields.FormField(IngredientForm), min_entries=1)
    methods =  fields.FieldList(fields.FormField(MethodForm), min_entries=1)


class ImageRecipeForm(FlaskForm):
    image = fields.FileField('Image')

bhagsahan/views/recipe.py
from flask import (Blueprint, 
                   request, 
                   render_template, 
                   redirect, 
                   url_for,
                   current_app,
                   Flask,
                   Response,
                   send_file)
from .. import models
from bhagsahan.forms import RecipeForm, ListForm, ImageRecipeForm
from werkzeug.security import generate_password_hash, check_password_hash
from flask import Flask, redirect, url_for, session, request, jsonify
from flask_login import logout_user, current_user, login_required


import datetime


module = Blueprint('recipe', __name__, url_prefix='/')



@module.route('/recipe')
@login_required
def recipe():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    recipes = models.Recipe.objects()
    if not user:
        return redirect(url_for('user.initial_user'))
    return render_template('recipe/recipe.html',
                           recipes=recipes,
                           user=user)
    
    
@module.route('/recipe_info/<recipe_id>')
@login_required
def recipe_info(recipe_id):
    user = models.User.objects.get(id=current_user._get_current_object().id)
    recipe = models.Recipe.objects().get(id=recipe_id)
    if not user:
        return redirect(url_for('user.initial_user'))
    return render_template('recipe/recipe_info.html',
                           recipe=recipe,
                           user=user)


@module.route('/add_recipe', methods=['GET', 'POST'])
@login_required
def add_recipe():
    form = RecipeForm()
    user = models.User.objects.get(id=current_user._get_current_object().id)
    if not user:
        return redirect(url_for('user.initial_user'))
    if not form.validate_on_submit():
        return render_template('recipe/add_recipe.html',
                               form=form,
                               user=user)
    if not form.description.data:
        form.description.data = '-'
    
    return redirect(url_for('recipe.add_list',
                            name=form.name.data,
                            description=form.description.data,
                            tags=form.tags.data,
                            calories=form.calories.data,
                            unit=form.unit.data,
                            ingredient_num=form.ingredient_num.data,
                            methods_num=form.methods_num.data,
                            food_type=form.food_type.data))


@module.route('/add_recipe/add_list/<name>/<description>/<tags>/<int:calories>/<unit>/<int:ingredient_num>/<int:methods_num>/<food_type>',
              methods=['GET', 'POST'])
@login_required
def add_list(name,
             description,
             tags,
             calories,
             unit,
             ingredient_num,
             methods_num,
             food_type):
    user = models.User.objects.get(id=current_user._get_current_object().id)
    form = ListForm()

    for i in range(len(form.ingredients), ingredient_num):
        form.ingredients.append_entry()
    
    for i in range(len(form.methods), methods_num):
        form.methods.append_entry()

    if not user:
        return redirect(url_for('user.initial_user'))
    if not form.validate_on_submit():
        return render_template('recipe/add_list.html',
                               form=form,
                               user=user)
    
    recipe = models.Recipe()
    

    new_srt = tags.strip()
    if new_srt.endswith(','):
        new_srt = new_srt[:-1]
    if new_srt.startswith(','):
        new_srt = new_srt[1:]
    ltags = [tag for tag in  new_srt.split(',') if tag != '']

    new_ingretients = []
    for ingredients_entry in form.ingredients.entries:
        ingredient = models.Ingredient()
        ingredient.name = ingredients_entry.in_name.data
        ingredient.volume = ingredients_entry.volume.data
        ingredient.amount_type = ingredients_entry.amount_type.data
        # recipe.ingredients.append(ingredient)
        new_ingretients.append(ingredient)

    for methods_entry in form.methods.entries:
        recipe.methods.append(methods_entry.info.data)

    recipe.name = name
    recipe.description = description
    recipe.tags = ltags
    recipe.calories = calories
    recipe.unit = unit
    recipe.ingredients = new_ingretients
    if food_type == 'Side dish':
        recipe.side_dish = True    
    recipe.created_date = datetime.datetime.now()
    recipe.update_date = datetime.datetime.now()
    recipe.save()
    
    # item = models.Item(name=name,
    #                    description=description,
    #                    tags=ltags,
    #                    created_date=datetime.datetime.now(),
    #                    updated_date=datetime.datetime.now())
    # item.save()
    
    # nutrition_fact = models.NutritionFact(calories=calories)
    
    # nutrition = models.Nutrition(item=item,
    #                              facts=nutrition_fact,
    #                              created_date=datetime.datetime.now(),
    #                              updated_date=datetime.datetime.now())
    # nutrition.save()

    return redirect(url_for('recipe.add_image_recipe',
                            recipe_id=recipe.id))

@module.route('/edit_recipe/<recipe_id>', methods=['GET', 'POST'])
@login_required
def edit_recipe(recipe_id):
    form = RecipeForm()
    user = models.User.objects.get(id=current_user._get_current_object().id)
    recipe = models.Recipe.objects().get(id=recipe_id)
    if not user:
        return redirect(url_for('user.initial_user'))

    if not form.validate_on_submit():
        form.name.data = recipe.name
        form.description.data = recipe.description
        form.tags.data = ','.join(recipe.tags)
        form.calories.data = recipe.calories
        form.unit.data = recipe.unit
        form.ingredient_num.data = len(recipe.ingredients)
        form.methods_num.data = len(recipe.methods)
        if recipe.side_dish:
            form.food_type.data = 'Side dish'

        
        return render_template('recipe/edit_recipe.html',
                               form=form,
                               recipe=recipe,
                               user=user)
    
    return redirect(url_for('recipe.edit_list',
                            recipe_id=recipe_id,
                            name=form.name.data,
                            description=form.description.data,
                            tags=form.tags.data,
                            calories=form.calories.data,
                            unit=form.unit.data,
                            ingredient_num=form.ingredient_num.data,
                            methods_num=form.methods_num.data,
                            food_type=form.food_type.data))




@module.route('/edit_recipe/add_list/<recipe_id>/<name>/<description>/<tags>/<int:calories>/<unit>/<int:ingredient_num>/<int:methods_num>/<food_type>',
              methods=['GET', 'POST'])
@login_required
def edit_list(recipe_id,
              name,
              description,
              tags,
              calories,
              unit,
              ingredient_num,
              methods_num,
              food_type):
    user = models.User.objects.get(id=current_user._get_current_object().id)
    form = ListForm()
    recipe = models.Recipe.objects().get(id=recipe_id)

    for i in range(len(form.ingredients), ingredient_num):
        form.ingredients.append_entry()
    
    for i in range(len(form.methods), methods_num):
        form.methods.append_entry()            

    if not user:
        return redirect(url_for('user.initial_user'))
    if not form.validate_on_submit():
        for ingredients_entry in form.ingredients.entries:
            if len(recipe.ingredients) > form.ingredients.entries.index(ingredients_entry):
                ingredients_entry.in_name.data = recipe.ingredients[form.ingredients.entries.index(ingredients_entry)].name
                ingredients_entry.volume.data = recipe.ingredients[form.ingredients.entries.index(ingredients_entry)].volume
                ingredients_entry.amount_type.data = recipe.ingredients[form.ingredients.entries.index(ingredients_entry)].amount_type

        for methods_entry in form.methods.entries:
            if len(recipe.methods) > form.methods.entries.index(methods_entry):
                methods_entry.info.data = recipe.methods[form.methods.entries.index(methods_entry)]
        
        return render_template('recipe/edit_list.html',
                               form=form,
                               user=user)

    new_srt = tags.strip()
    if new_srt.endswith(','):
        new_srt = new_srt[:-1]
    if new_srt.startswith(','):
        new_srt = new_srt[1:]
    ltags = [tag for tag in  new_srt.split(',') if tag != '']

    new_ingredient = []
    for ingredients_entry in form.ingredients.entries:
        ingredient = models.Ingredient()
        ingredient.name = ingredients_entry.in_name.data
        ingredient.volume = ingredients_entry.volume.data
        ingredient.amount_type = ingredients_entry.amount_type.data
        new_ingredient.append(ingredient)

    update_methods = []
    for methods_entry in form.methods.entries:
        update_methods.append(methods_entry.info.data)
    
    for i in new_ingredient:
        print(i.name)
        
    recipe.name = name
    recipe.description = description
    recipe.tags = ltags
    recipe.calories = calories
    recipe.unit = unit
    recipe.ingredients = new_ingredient
    recipe.methods = update_methods
    if food_type == 'Side dish':
        recipe.side_dish = True
    recipe.created_date = datetime.datetime.now()
    recipe.update_date = datetime.datetime.now()
    recipe.save()

    return redirect(url_for('recipe.edit_image_recipe',
                            recipe_id=recipe_id))
    
    
@module.route('/add_image_recipe/<recipe_id>', methods=['GET', 'POST'])
@login_required
def add_image_recipe(recipe_id):

bhagsahan/templates/recipe/add_image.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
        <div class="row">
          <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
            <div class="card white z-depth-3">
              <div class="card-content">
                <span class="card-title">Add Image Recipe</span>
                <form enctype="multipart/form-data" method="POST">
                {{form.csrf_token}}
                  <div class="row" style="margin-top: 2%">
                    <div class="file-field col input-field s12 m12">
                        <div class="green darken-4 btn btn-primary">
                            {{ form.image() }}
                            {{ form.image.label }}  
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                        </div>
                    </div>
                  <div class="row">
                    <button class="green darken-4 btn btn-primary col s12 m6 l6 xl6 offset-m3 offset-l3 offset-xl3" type="submit">Submit</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div class="right">
                <a href="{{url_for('recipe.recipe_info', recipe_id=recipe.id)}}" class="waves-effect waves-light btn">Continue</a>
          </div>
        </div>
    </div>
      
{% endblock %}

bhagsahan/templates/recipe/add_list.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
    <form enctype="multipart/form-data" method="POST">
    {{form.csrf_token}}
        <div class="row">
          <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
            <div class="card white z-depth-3">
              <div class="card-content">
                <span class="card-title">Add Ingredient</span>
                  {% for subform in form.ingredients %}
                  <div class="row" style="margin-top: 2%">
                    <div class="input-field col s12 m12">
                      {{subform.in_name}}
                      {{subform.in_name.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{subform.volume}}
                      {{subform.volume.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{subform.amount_type}}
                      {{subform.amount_type.label}}
                    </div>
                 </div>
                 {% endfor %}
              </div>
            </div>
          </div>
          <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
                <div class="card white z-depth-3">
                  <div class="card-content">
                    <span class="card-title">Add Method</span>
                    {% for subform in form.methods %}
                      <div class="row" style="margin-top: 2%">
                        <div class="input-field col s12 m12">
                          {{subform.info}}
                          {{subform.info.label}}
                        </div>
                    </div>
                    {% endfor %}
                  </div>
                </div>
          </div>
          <div class="row">
            <button class="green darken-4 btn btn-primary col s12 m6 l6 xl6 offset-m3 offset-l3 offset-xl3" type="submit">Submit</button>
          </div>
        </div>
    </form>
    </div>

{% endblock %}

bhagsahan/templates/recipe/add_recipe.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
        <div class="row">
          <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
            <div class="card white z-depth-3">
              <div class="card-content">
                <span class="card-title">Add More Recipe</span>
                <form enctype="multipart/form-data" method="POST">
                {{form.csrf_token}}
                  <div class="row" style="margin-top: 2%">
                    <div class="input-field col s12 m12">
                      {{form.name}}
                      {{form.name.label}}
                    </div>
                    <div class="input-field col s12 m12">
                      {{form.description}}
                      {{form.description.label}}
                    </div>
                    <div class="input-field col s12 m12">
                      {{form.tags}}
                      {{form.tags.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.calories}}
                      {{form.calories.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.unit}}
                      {{form.unit.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.ingredient_num}}
                      {{form.ingredient_num.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.methods_num}}
                      {{form.methods_num.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.food_type}}
                      {{form.food_type.label}}
                    </div>
                  <div class="row">
                    <button class="green darken-4 btn btn-primary col s12 m6 l6 xl6 offset-m3 offset-l3 offset-xl3" type="submit">Submit</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
    </div>
      
{% endblock %}

bhagsahan/templates/recipe/edit_image.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
        <div class="row">
          <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
            <div class="card white z-depth-3">
              <div class="card-content">
                <span class="card-title">Edit Image Recipe</span>
                <form enctype="multipart/form-data" method="POST">
                {{form.csrf_token}}
                  <div class="row" style="margin-top: 2%">
                    <div class="file-field col input-field s12 m12">
                        <div class="green darken-4 btn btn-primary">
                            {{ form.image() }}
                            {{ form.image.label }}  
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                        </div>
                    </div>
                  <div class="row">
                    <button class="green darken-4 btn btn-primary col s12 m6 l6 xl6 offset-m3 offset-l3 offset-xl3" type="submit">Submit</button>
                    
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div class="right">
                <a href="{{url_for('recipe.recipe_info', recipe_id=recipe.id)}}" class="waves-effect waves-light btn">Continue</a>
          </div>
        </div>
    </div>
      
{% endblock %}

bhagsahan/templates/recipe/edit_list.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
    <form enctype="multipart/form-data" method="POST">
    {{form.csrf_token}}
        <div class="row">
          <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
            <div class="card white z-depth-3">
              <div class="card-content">
                <span class="card-title">Edit Ingredient</span>
                  {% for subform in form.ingredients %}
                  <div class="row" style="margin-top: 2%">
                    <div class="input-field col s12 m12">
                      {{subform.in_name}}
                      {{subform.in_name.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{subform.volume}}
                      {{subform.volume.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{subform.amount_type}}
                      {{subform.amount_type.label}}
                    </div>
                 </div>
                 {% endfor %}
              </div>
            </div>
          </div>
          <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
                <div class="card white z-depth-3">
                  <div class="card-content">
                    <span class="card-title">Edit Method</span>
                    {% for subform in form.methods %}
                      <div class="row" style="margin-top: 2%">
                        <div class="input-field col s12 m12">
                          {{subform.info}}
                          {{subform.info.label}}
                        </div>
                    </div>
                    {% endfor %}
                  </div>
                </div>
          </div>
          <div class="row">
            <button class="green darken-4 btn btn-primary col s12 m6 l6 xl6 offset-m3 offset-l3 offset-xl3" type="submit">Submit</button>
          </div>
        </div>
    </form>
    </div>

{% endblock %}

bhagsahan/templates/recipe/edit_recipe.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
        <div class="row">
          <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
            <div class="card white z-depth-3">
              <div class="card-content">
                <span class="card-title">Edit Recipe</span>
                <div class="col s12">
                  <a href="#modalDelete" class="right modal-trigger red btn" style="border-radius: 5px"><i class="material-icons">delete</i>Delete</a>
                </div>
                <form enctype="multipart/form-data" method="POST">
                {{form.csrf_token}}
                  <div class="row" style="margin-top: 2%">
                    <div class="input-field col s12 m12">
                      {{form.name}}
                      {{form.name.label}}
                    </div>
                    <div class="input-field col s12 m12">
                      {{form.description}}
                      {{form.description.label}}
                    </div>
                    <div class="input-field col s12 m12">
                      {{form.tags}}
                      {{form.tags.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.calories}}
                      {{form.calories.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.unit}}
                      {{form.unit.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.ingredient_num}}
                      {{form.ingredient_num.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.methods_num}}
                      {{form.methods_num.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.food_type}}
                      {{form.food_type.label}}
                    </div>
                  <div class="row">
                    <button class="green darken-4 btn btn-primary col s12 m6 l6 xl6 offset-m3 offset-l3 offset-xl3" type="submit">Submit</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
    </div>
    <div id="modalDelete" class="modal">
      <div class="modal-content">
        <div class="row center">
          <h5>Do you want to delete this information?</h5>
        </div>
        <div class="row center">
          <a class="btn light-blue darken-4 z-depth-0" href="{{ url_for('recipe.delete_recipe', recipe_id=recipe.id) }}">Yes</a>
          <a class="btn red darken-2 z-depth-0 modal-close" >No</a>
        </div>
      </div>
    </div>
      
{% endblock %}

bhagsahan/templates/recipe/recipe.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
            <span style="font-size: 1.64rem">Recipe</span>
            <div class="divider"></div>
        <div class="card grey lighten-5" style="margin-top: 3%">
            <div class="container">
                <div class="row">
                    <table>
                        <thead>
                            <tr>
                                <th>Recipe Name</th>
                                <th>Calories</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for recipe in recipes %}
                            <tr>
                                <td>{{ recipe.name }}</td>
                                <td>{{ recipe.calories }} / {{ recipe.unit }}</td>
                                <td><a class="btn-floating btn-small" style="background-color:#1E3B4C" href="{{ url_for('recipe.recipe_info', recipe_id=recipe.id) }}"><i class="material-icons">description</i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>  
        </div>
    </div>
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large red" href="{{ url_for('recipe.add_recipe') }}" >
          <i class="large material-icons">add_to_photos</i>
        </a>
    </div>
{% endblock %}

bhagsahan/templates/recipe/recipe_info.html
{% extends "/base/base_layout.html" %}
{% block content %}
<div class="container" style="margin-top: 5%">
  <div class="row">
    <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
      <div class="card white z-depth-3">
        <div class="card-content">
          <span class="card-title">Recipe</span>
            <div class="row" style="margin-top: 2%">
              <div class="col s6 m6">
                {% if recipe.image %}
                  <img class="activator" width="300" height="310" src="{{ url_for('recipe.recipe_image', recipe_id=recipe.id, file_name=recipe.image.filename) }}" >
                {% else %}
                  <img class="activator" width="300" height="310" src="{{ url_for('static', filename='images/undraw_Hamburger_8ge6.png') }}" >
                {% endif %}
              </div>
              <div class="col s6 m6">
                    <div class="input-field col s12 m12">
                      Name : 
                      {{ recipe.name }}
                    </div>
                    <div class="input-field col s12 m12">
                      Food Type : 
                      {% if recipe.side_dish %}
                        Side dish
                      {% else %}
                        A la carte
                      {% endif %}
                    </div>
                    <div class="input-field col s12 m12">
                      Description : 
                      {{ recipe.description }}
                    </div>
                    <div class="input-field col s12 m12">
                      Tags : 
                      {% for tag in recipe.tags %}
                        {{ tag }}
                      {% endfor %}
                    </div>
                    <div class="input-field col s6 m6">
                      Calories : 
                      {{ recipe.calories }} / {{ recipe.unit }}
                    </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
      <div class="card white z-depth-3">
        <div class="card-content">
          <span class="card-title">Ingredients</span>
            <div class="row" style="margin-top: 2%">
                {% for ingredient in recipe.ingredients %}    
                <div class="input-field col s12 m12">
                     {{ loop.index }} : {{ ingredient.name }}  {{ ingredient.volume }}  {{ ingredient.amount_type }}
                </div>
                {% endfor %}
            </div>
        </div>
        </div>
    </div>

    <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
      <div class="card white z-depth-3">
        <div class="card-content">
          <span class="card-title">Methods</span>
            <div class="row" style="margin-top: 2%">
                {% for method in recipe.methods %}
                <div class="input-field col s12 m12">
                  {{ loop.index }} : {{ method }}
                </div>
                {% endfor %}
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="fixed-action-btn">
  <a class="btn-floating btn-large red" href="{{ url_for('recipe.edit_recipe', recipe_id=recipe.id) }}" >
    <i class="large material-icons">mode_edit</i>
  </a>
</div>
{% endblock %}