bhagsahan/models/food.py
import mongoengine as me
import datetime
from . import users

class RestaurantFoodGroup(me.EmbeddedDocument):
    protein = me.BooleanField(required=True, default=False)
    carbohydrate = me.BooleanField(required=True, default=False)
    vitamin = me.BooleanField(required=True, default=False)
    mineral = me.BooleanField(required=True, default=False)
    fat = me.BooleanField(required=True, default=False)

class Food(me.Document):
    meta = {'collection': 'food'}
    
    name = me.StringField(required=True)
    description = me.StringField()
    restaurant = me.StringField()
    calories = me.IntField(required=True, default=0)
    tags = me.ListField(me.StringField())
    image = me.FileField()
    food_group = me.EmbeddedDocumentField(RestaurantFoodGroup)
    user_created = me.ReferenceField(users.User, dbref=True)
    
    
    created_date = me.DateTimeField(required=True,
                                    default=datetime.datetime.utcnow)
    update_date = me.DateTimeField(required=True,
                                   default=datetime.datetime.utcnow)

bhagsahan/forms/food.py
from flask_wtf import FlaskForm
from wtforms import fields
from wtforms import validators
import datetime


class FoodForm(FlaskForm):
    name = fields.TextField('Food Name',
                             validators=[validators.InputRequired()])
    description = fields.TextField('Description')
    restaurant = fields.TextField('Resturant',
                                  validators=[validators.InputRequired()])
    calories = fields.IntegerField('Calories',
                                            validators=[validators.InputRequired()])
    tags = fields.TextField('Tags')
    image = fields.FileField('Image')
    
    protein = fields.BooleanField('Protein')
    carbohydrate = fields.BooleanField('Carbohydrate')
    vitamin = fields.BooleanField('Vitamin')
    mineral = fields.BooleanField('Mineral')
    fat = fields.BooleanField('Fat')

bhagsahan/views/food.py
from flask import (Blueprint, 
                   request, 
                   render_template, 
                   redirect, 
                   url_for,
                   current_app,
                   Flask,
                   Response,
                   send_file)
from .. import models
from mongoengine.queryset.visitor import Q
from bhagsahan.forms import SelectMoreFoodForm, FoodForm, SetTime
from werkzeug.security import generate_password_hash, check_password_hash
from flask import Flask, redirect, url_for, session, request, jsonify
from flask_login import logout_user, current_user, login_required



import datetime


module = Blueprint('food', __name__, url_prefix='/')


@module.route('/another_food', methods=['GET', 'POST'])
@login_required
def another_food():
    form = SelectMoreFoodForm()
    user = models.User.objects.get(id=current_user._get_current_object().id)

    if not form.validate_on_submit():
        return render_template('food/another_food.html',
                                user=user,
                                form=form)

    if form.cal_in.data > 0:
        user.cal_limit -= form.cal_in.data
        user.cal_limit_per_week -= form.cal_in.data
        user.calories_in += form.cal_in.data
        if user.cal_limit < 0:
            user.cal_limit = 0
        if user.cal_limit_per_week < 0:
            user.cal_limit_per_week = 0
        user.save()
        
        eating_log = models.EatingLog(user=user,
                                      food_name=form.food_name.data,
                                      calories=form.cal_in.data,
                                      category='Food from outside',
                                      created_date=datetime.datetime.now(),
                                      update_date=datetime.datetime.now())
        day = int(form.date_eat.data.strftime('%d'))
        month = int(form.date_eat.data.strftime('%m'))
        year = int(form.date_eat.data.strftime('%Y'))
        hour = int(form.time_eat.data.strftime('%H'))
        minute = int(form.time_eat.data.strftime('%M'))
        eating_log.datetime_eat = datetime.datetime(year, month, day, hour, minute)
        eating_log.save()

        
                                      
        return redirect(url_for('eating_log.eating_list'))



@module.route('/food_list')
@login_required
def food_list():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    food = models.Food.objects()
    if not user:
        return redirect(url_for('user.initial_user'))
    return render_template('food/food_list.html',
                           food=food,
                           user=user)


@module.route('/food_list_order')
@login_required
def food_list_order():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    food = models.Food.objects().order_by('calories')
    if not user:
        return redirect(url_for('user.initial_user'))
    return render_template('food/food_list_order.html',
                           food=food,
                           user=user)


@module.route('/food_list_recommend')
@login_required
def food_list_recommend():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    food = models.Food.objects(Q(calories__lte=600))
    if not user:
        return redirect(url_for('user.initial_user'))
    return render_template('food/food_list_recommend.html',
                           food=food,
                           user=user)


@module.route('/food_information/<food_id>')
@login_required
def food_information(food_id):
    user = models.User.objects.get(id=current_user._get_current_object().id)
    food = models.Food.objects().get(id=food_id)
    if not user:
        return redirect(url_for('user.initial_user'))
    return render_template('food/food_information.html',
                           food=food,
                           user=user)
    

@module.route('/add_food', methods=['GET', 'POST'])
@login_required
def add_food():
    form = FoodForm()
    user = models.User.objects.get(id=current_user._get_current_object().id)
    if not user:
        return redirect(url_for('user.initial_user'))
    if not form.validate_on_submit():
        return render_template('food/add_food.html',
                               form=form,
                               user=user)
    
    new_srt = form.tags.data.strip()
    if new_srt.endswith(','):
        new_srt = new_srt[:-1]
    if new_srt.startswith(','):
        new_srt = new_srt[1:]
    ltags = [tag for tag in  new_srt.split(',') if tag != '']

    food_group = models.RestaurantFoodGroup(protein=form.protein.data,
                                  carbohydrate=form.carbohydrate.data,
                                  vitamin=form.vitamin.data,
                                  mineral=form.mineral.data,
                                  fat=form.fat.data)
    
    new_food = models.Food(name=form.name.data,
                           description=form.description.data,
                           restaurant=form.restaurant.data,
                           calories=form.calories.data,
                           tags=ltags,
                           food_group=food_group,
                           user_created=user,
                           created_date=datetime.datetime.now(),
                           update_date=datetime.datetime.now())
    if form.image.data:
        new_food.image.put(form.image.data,
                            filename=form.image.data.filename)
    new_food.save()
    
    

    return redirect(url_for('food.food_information',
                            food_id=new_food.id))
    

@module.route('/edit_food/<food_id>', methods=['GET', 'POST'])
@login_required
def edit_food(food_id):
    form = FoodForm()
    user = models.User.objects.get(id=current_user._get_current_object().id)
    food = models.Food.objects.get(id=food_id)
    if not user:
        return redirect(url_for('user.initial_user'))
    if not form.validate_on_submit():
        form.name.data = food.name
        form.description.data = food.description
        form.restaurant.data = food.restaurant
        form.calories.data = food.calories
        form.tags.data = ",".join(food.tags)
        form.image.data = food.image
        
        if not food.food_group:
            form.protein.data = False
            form.carbohydrate.data = False
            form.vitamin.data = False
            form.mineral.data = False
            form.fat.data = False
        else:
            form.protein.data = food.food_group.protein
            form.carbohydrate.data = food.food_group.carbohydrate
            form.vitamin.data = food.food_group.vitamin
            form.mineral.data = food.food_group.mineral
            form.fat.data = food.food_group.fat

        return render_template('food/edit_food.html',
                               form=form,
                               user=user,
                               food=food)
    
    new_srt = form.tags.data.strip()
    if new_srt.endswith(','):
        new_srt = new_srt[:-1]
    if new_srt.startswith(','):
        new_srt = new_srt[1:]
    ltags = [tag for tag in  new_srt.split(',') if tag != '']

    food.name = form.name.data
    food.description = form.description.data
    food.restaurant = form.restaurant.data
    food.calories = form.calories.data
    food.tags = ltags
    if form.image.data:
        food.image.replace(form.image.data,
                           filename=form.image.data.filename)

    food_group = models.RestaurantFoodGroup(protein=form.protein.data,
                                            carbohydrate=form.carbohydrate.data,
                                            vitamin=form.vitamin.data,
                                            mineral=form.mineral.data,
                                            fat=form.fat.data)    
    food.food_group = food_group
    food.update_date = datetime.datetime.now()
    food.save()
    
    

    return redirect(url_for('food.food_information',
                            food_id=food.id))


@module.route('/delete_food/<food_id>', methods=['GET', 'POST'])
def delete_food(food_id):
    food = models.Food.objects.get(id=food_id)
    food.delete()

    return redirect(url_for('food.food_list'))


@module.route('/select_food/<food_id>', methods=['GET', 'POST'])
def select_food(food_id):
    form = SetTime()
    user = models.User.objects.get(id=current_user._get_current_object().id)
    food = models.Food.objects.get(id=food_id)
    if not form.validate_on_submit():
        return render_template('food/set_time.html',
                               form=form,
                               user=user)

    eating_log = models.EatingLog(user=user,
                                  food_name=food.name,
                                  calories=food.calories,
                                  category='Restaurant',
                                  food_infomation=food,
                                  created_date=datetime.datetime.now(),
                                  update_date=datetime.datetime.now())
    day = int(form.date_eat.data.strftime('%d'))
    month = int(form.date_eat.data.strftime('%m'))
    year = int(form.date_eat.data.strftime('%Y'))
    hour = int(form.time_eat.data.strftime('%H'))
    minute = int(form.time_eat.data.strftime('%M'))
    eating_log.datetime_eat = datetime.datetime(year, month, day, hour, minute)
    eating_log.save()
    
    if food.calories > 0:
        user.cal_limit -= food.calories
        user.cal_limit_per_week -= food.calories
        user.calories_in += food.calories
        if user.cal_limit < 0:
            user.cal_limit = 0
        if user.cal_limit_per_week < 0:
            user.cal_limit_per_week = 0

    if food.food_group.protein:
        user.food_group.protein = True
    if food.food_group.carbohydrate:
        user.food_group.carbohydrate = True
    if food.food_group.vitamin:

bhagsahan/templates/food/food_list.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 3%">
        <span style="font-size: 1.64rem">Food that you've already eaten</span>
        <div class="divider"></div>
        <ul class="pagination">
            <li class="waves-effect"><a href="{{ url_for('food.another_food') }}">What did you get</a></li>
            <li class="active"><a href="#!">Food previously</a></li>
        </ul>
        <ul class="pagination">
            <li class="active"><a href="#!">All</a></li>
            <li class="waves-effect"><a href="{{ url_for('food.food_list_order') }}">Order by calories</a></li>
            <li class="waves-effect"><a href="{{ url_for('food.food_list_recommend') }}">Recommend</a></li>
        </ul>
        <div class="row" style="margin-top: 3%">
            <div class="col s12 m12">
                <nav class="white">
                <div class="nav-wrapper">
                    <form action="{{ url_for('food.search_result') }}" method="GET">
                    <div class="input-field">
                        <input id="search" type="search" name="search" placeholder="Find your food" class="validate search-field">
                        <label class="label-icon" for="search"><i class="material-icons black-text">search</i></label>
                        <input type="submit" class="hide">
                        <i class="material-icons close-btn">close</i>
                    </div>
                    </form>
                </div>
                </nav>
            </div>
        </div>
        <div class="card grey lighten-5" style="margin-top: 3%" >
            <div class="container">
                <div class="row">
                    <table>
                        <thead>
                            <tr>
                                <th>Food Name</th>
                                <th>Calories</th>
                                <th>Restaurant</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for f in food %}
                            <tr>
                                <td>{{ f.name }}</td>
                                <td>{{ f.calories }}</td>
                                <td>{{ f.restaurant }}</td>
                                <td>
                                    <a class="btn-floating btn-small" 
                                    style="background-color:#1E3B4C" 
                                    href="{{ url_for('food.food_information', food_id=f.id) }}">
                                     <i class="material-icons">description</i>
                                    </a></td>
                                <td>
                                    {% if f.calories <= 600 %}
                                        <a><span class="green-text name">Calories Recommended</span></a>
                                    {% endif %}
                                    </td>
                                <td>
                                    <a href="#modalSelect{{ f.id }}" class="right modal-trigger red btn" style="border-radius: 5px">
                                        <i class="material-icons left">check</i>Select
                                    </a></td>
                            </tr>
                            <div id="modalSelect{{ f.id }}" class="modal">
                                <div class="modal-content">
                                  <div class="row center">
                                    <h5>Do you want to select this food?</h5>
                                  </div>
                                  <div class="row center">
                                    <a class="btn light-blue darken-4 z-depth-0" href="{{ url_for('food.select_food', food_id=f.id) }}">Yes</a>
                                    <a class="btn red darken-2 z-depth-0 modal-close" >No</a>
                                  </div>
                                </div>
                              </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>  
        </div>
    </div>
</div>


<div class="fixed-action-btn">
<a class="btn-floating btn-large btn modal-trigger red lighten-1" href="{{ url_for('food.add_food') }}" >
    <i class="large material-icons">move_to_inbox</i>
</a >
</div>



{% endblock %}

bhagsahan/templates/food/food_list_order.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 3%">
        <span style="font-size: 1.64rem">Food that you've already eaten</span>
        <div class="divider"></div>
        <ul class="pagination">
            <li class="waves-effect"><a href="{{ url_for('food.another_food') }}">What did you get</a></li>
            <li class="active"><a href="#!">Food previously</a></li>
        </ul>
        <ul class="pagination">
            <li class="waves-effect"><a href="{{ url_for('food.food_list') }}">All</a></li>
            <li class="active"><a href="#!">Order by calories</a></li>
            <li class="waves-effect"><a href="{{ url_for('food.food_list_recommend') }}">Recommend</a></li>
        </ul>
        <div class="row" style="margin-top: 3%">
            <div class="col s12 m12">
                <nav class="white">
                <div class="nav-wrapper">
                    <form action="{{ url_for('food.search_result') }}" method="GET">
                    <div class="input-field">
                        <input id="search" type="search" name="search" placeholder="Find your food" class="validate search-field">
                        <label class="label-icon" for="search"><i class="material-icons black-text">search</i></label>
                        <input type="submit" class="hide">
                        <i class="material-icons close-btn">close</i>
                    </div>
                    </form>
                </div>
                </nav>
            </div>
        </div>
        <div class="card grey lighten-5" style="margin-top: 3%" >
            <div class="container">
                <div class="row">
                    <table>
                        <thead>
                            <tr>
                                <th>Food Name</th>
                                <th>Calories</th>
                                <th>Restaurant</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for f in food %}
                            <tr>
                                <td>{{ f.name }}</td>
                                <td>{{ f.calories }}</td>
                                <td>{{ f.restaurant }}</td>
                                <td>
                                    <a class="btn-floating btn-small" 
                                    style="background-color:#1E3B4C" 
                                    href="{{ url_for('food.food_information', food_id=f.id) }}">
                                     <i class="material-icons">description</i>
                                    </a></td>
                                <td>
                                    {% if f.calories <= 600 %}
                                        <a><span class="green-text name">Calories Recommended</span></a>
                                    {% endif %}
                                    </td>
                                <td>
                                    <a href="#modalSelect" class="right modal-trigger red btn" style="border-radius: 5px">
                                        <i class="material-icons">check</i>Select this food
                                    </a></td>
                            </tr>
                            <div id="modalSelect" class="modal">
                                <div class="modal-content">
                                  <div class="row center">
                                    <h5>Do you want to select this food?</h5>
                                  </div>
                                  <div class="row center">
                                    <a class="btn light-blue darken-4 z-depth-0" href="{{ url_for('food.select_food', food_id=f.id) }}">Yes</a>
                                    <a class="btn red darken-2 z-depth-0 modal-close" >No</a>
                                  </div>
                                </div>
                              </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>  
        </div>
    </div>
</div>


<div class="fixed-action-btn">
<a class="btn-floating btn-large btn modal-trigger red lighten-1" href="{{ url_for('food.add_food') }}" >
    <i class="large material-icons">move_to_inbox</i>
</a >
</div>



{% endblock %}

bhagsahan/templates/food/food_list_recommend.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 3%">
        <span style="font-size: 1.64rem">Food that you've already eaten</span>
        <div class="divider"></div>
        <ul class="pagination">
            <li class="waves-effect"><a href="{{ url_for('food.another_food') }}">What did you get</a></li>
            <li class="active"><a href="#!">Food previously</a></li>
        </ul>
        <ul class="pagination">
            <li class="waves-effect"><a href="{{ url_for('food.food_list') }}">All</a></li>
            <li class="waves-effect"><a href="{{ url_for('food.food_list_order') }}">Order by calories</a></li>
            <li class="active"><a href="#!">Recommend</a></li>
        </ul>
        <div class="row" style="margin-top: 3%">
            <div class="col s12 m12">
                <nav class="white">
                <div class="nav-wrapper">
                    <form action="{{ url_for('food.search_result') }}" method="GET">
                    <div class="input-field">
                        <input id="search" type="search" name="search" placeholder="Find your food" class="validate search-field">
                        <label class="label-icon" for="search"><i class="material-icons black-text">search</i></label>
                        <input type="submit" class="hide">
                        <i class="material-icons close-btn">close</i>
                    </div>
                    </form>s
                </div>
                </nav>
            </div>
        </div>
        <div class="card grey lighten-5" style="margin-top: 3%" >
            <div class="container">
                <div class="row">
                    <table>
                        <thead>
                            <tr>
                                <th>Food Name</th>
                                <th>Calories</th>
                                <th>Restaurant</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for f in food %}
                            <tr>
                                <td>{{ f.name }}</td>
                                <td>{{ f.calories }}</td>
                                <td>{{ f.restaurant }}</td>
                                <td>
                                    <a class="btn-floating btn-small" 
                                    style="background-color:#1E3B4C" 
                                    href="{{ url_for('food.food_information', food_id=f.id) }}">
                                     <i class="material-icons">description</i>
                                    </a></td>
                                <td>
                                    {% if f.calories <= 600 %}
                                        <a><span class="green-text name">Calories Recommended</span></a>
                                    {% endif %}
                                    </td>
                                <td>
                                    <a href="#modalSelect" class="right modal-trigger red btn" style="border-radius: 5px">
                                        <i class="material-icons">check</i>Select this food
                                    </a></td>
                            </tr>
                            <div id="modalSelect" class="modal">
                                <div class="modal-content">
                                  <div class="row center">
                                    <h5>Do you want to select this food?</h5>
                                  </div>
                                  <div class="row center">
                                    <a class="btn light-blue darken-4 z-depth-0" href="{{ url_for('food.select_food', food_id=f.id) }}">Yes</a>
                                    <a class="btn red darken-2 z-depth-0 modal-close" >No</a>
                                  </div>
                                </div>
                              </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>  
        </div>
    </div>
</div>


<div class="fixed-action-btn">
<a class="btn-floating btn-large btn modal-trigger red lighten-1" href="{{ url_for('food.add_food') }}" >
    <i class="large material-icons">move_to_inbox</i>
</a >
</div>



{% endblock %}

bhagsahan/templates/food/search_food.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 3%">
        <span style="font-size: 1.64rem">Food that you've already eaten</span>
        <div class="divider"></div>
        <ul class="pagination">
            <li class="waves-effect"><a href="{{ url_for('food.another_food') }}">What did you get</a></li>
            <li class="active"><a href="#!">Food previously</a></li>
        </ul>
        <ul class="pagination">
            <li class="active"><a href="#!">All</a></li>
            <li class="waves-effect"><a href="{{ url_for('food.food_list_order') }}">Order by calories</a></li>
            <li class="waves-effect"><a href="{{ url_for('food.food_list_recommend') }}">Recommend</a></li>
        </ul>
        <div class="row" style="margin-top: 3%">
            <div class="col s12 m12">
                <nav class="white">
                <div class="nav-wrapper">
                    <form action="{{ url_for('food.search_result') }}" method="GET">
                    <div class="input-field">
                        <input id="search" type="search" name="search" placeholder="Find your food" class="validate search-field">
                        <label class="label-icon" for="search"><i class="material-icons black-text">search</i></label>
                        <input type="submit" class="hide">
                        <i class="material-icons close-btn">close</i>
                    </div>
                    </form>
                </div>
                </nav>
            </div>
        </div>
        <div class="card grey lighten-5" style="margin-top: 3%" >
            <div class="container">
                <div class="row">
                    <table>
                        <thead>
                            <tr>
                                <th>Food Name</th>
                                <th>Calories</th>
                                <th>Restaurant</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for f in food %}
                            <tr>
                                <td>{{ f.name }}</td>
                                <td>{{ f.calories }}</td>
                                <td>{{ f.restaurant }}</td>
                                <td>
                                    <a class="btn-floating btn-small" 
                                    style="background-color:#1E3B4C" 
                                    href="{{ url_for('food.food_information', food_id=f.id) }}">
                                     <i class="material-icons">description</i>
                                    </a></td>
                                <td>
                                    {% if f.calories <= 600 %}
                                        <a><span class="green-text name">Calories Recommended</span></a>
                                    {% endif %}
                                    </td>
                                <td>
                                    <a href="#modalSelect" class="right modal-trigger red btn" style="border-radius: 5px">
                                        <i class="material-icons">check</i>Select this food
                                    </a></td>
                            </tr>
                            <div id="modalSelect" class="modal">
                                <div class="modal-content">
                                  <div class="row center">
                                    <h5>Do you want to select this food?</h5>
                                  </div>
                                  <div class="row center">
                                    <a class="btn light-blue darken-4 z-depth-0" href="{{ url_for('food.select_food', food_id=f.id) }}">Yes</a>
                                    <a class="btn red darken-2 z-depth-0 modal-close" >No</a>
                                  </div>
                                </div>
                              </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>  
        </div>
    </div>
</div>


<div class="fixed-action-btn">
<a class="btn-floating btn-large btn modal-trigger red lighten-1" href="{{ url_for('food.add_food') }}" >
    <i class="large material-icons">move_to_inbox</i>
</a >
</div>



{% endblock %}

bhagsahan/templates/food/set_time.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
        <div class="row">
          <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
            <div class="card white z-depth-3">
              <div class="card-content">
                <span class="card-title">Add More Food</span>
                <form enctype="multipart/form-data" method="POST">
                    {{form.csrf_token}}
                        <div class="input-field col s12 m12">
                            {{form.date_eat(class='datepicker')}}
                            {{form.date_eat.label}}
                        </div>
                        <div class="input-field col s12 m12">
                            {{form.time_eat(class='timepicker')}}
                            {{form.time_eat.label}}
                        </div>
                      <div class="row">
                        <button class="green darken-4 btn btn-primary col s6 m6 l6 xl6 offset-m3 offset-l3 offset-xl3" type="submit">Submit</button>
                      </div>
                    </form>
              </div>
            </div>
          </div>
        </div>
    </div>
{% endblock %}