bhagsahan/models/stock.py
import mongoengine as me
import datetime
from .nutrition import Nutrition


class Stock(me.Document):
    meta = {'collection': 'stock'}

    name = me.StringField(required=True)
    description = me.StringField()

    tags = me.ListField(me.StringField())
    volume = me.IntField()
    amount_type = me.StringField()
    stock_type = me.StringField()
    
    nutrition = me.ReferenceField(Nutrition, dbref=True)

    active = me.BooleanField(default=False)
    
    created_date = me.DateTimeField(required=True,
                                    default=datetime.datetime.utcnow)
    update_date = me.DateTimeField(required=True,
                                   default=datetime.datetime.utcnow)

bhagsahan/forms/stock.py
from flask_wtf import FlaskForm
from wtforms import fields
from wtforms import validators


class StockForm(FlaskForm):
    name = fields.TextField('Name',
                             validators=[validators.InputRequired()])
    description = fields.TextField('Description')
    tags = fields.TextField('Tags')
    
    volume = fields.IntegerField('Volume')
    amount_type = fields.TextField('Amount Type')
    
    stock_type = fields.SelectField('Stock type',
                                choices=[('instant food', 'Instant food'),
                                         ('ingredient', 'Ingredient')])

# class AddItemForm(FlaskForm):
#     volume = fields.IntegerField('Volume')

class IncreaseStockForm(FlaskForm):
    volume = fields.IntegerField('Volume')

    

bhagsahan/views/stock.py
from flask import (Blueprint, 
                   request, 
                   render_template, 
                   redirect, 
                   url_for,
                   current_app,
                   Flask)
from .. import models
from bhagsahan.forms import StockForm, IncreaseStockForm
from werkzeug.security import generate_password_hash, check_password_hash
from flask import Flask, redirect, url_for, session, request, jsonify
from flask_login import logout_user, current_user, login_required


import datetime


module = Blueprint('stock', __name__, url_prefix='/')



@module.route('/stock')
@login_required
def stock():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    stocks = models.Stock.objects()
    if not user:
        return redirect(url_for('user.initial_user'))
    return render_template('stock/stock.html',
                           stocks=stocks,
                           user=user)


@module.route('/stock_info/<stock_id>', methods=['GET', 'POST'])
@login_required
def stock_info(stock_id):
    user = models.User.objects.get(id=current_user._get_current_object().id)
    stock = models.Stock.objects().get(id=stock_id) 
    if not user:
        return redirect(url_for('user.initial_user'))
    return render_template('stock/stock_info.html',
                            stock=stock,
                            user=user)


@module.route('/add_stock', methods=['GET', 'POST'])
@login_required
def add_stock():
    form = StockForm()
    user = models.User.objects.get(id=current_user._get_current_object().id)
    if not user:
        return redirect(url_for('user.initial_user'))
    if not form.validate_on_submit():
        return render_template('stock/add_stock.html',
                               form=form,
                               user=user)
    
    new_srt = form.tags.data.strip()
    if new_srt.endswith(','):
        new_srt = new_srt[:-1]
    if new_srt.startswith(','):
        new_srt = new_srt[1:]
    ltags = [tag for tag in  new_srt.split(',') if tag != '']

    stock = models.Stock(name=form.name.data,
                         description=form.description.data,
                         tags=ltags,
                         volume=form.volume.data,
                         amount_type=form.amount_type.data,
                         stock_type=form.stock_type.data,
                         active=True,
                         created_date=datetime.datetime.now(),
                         update_date=datetime.datetime.now())

    nutritions = models.Nutrition.objects()
    for nutrition in nutritions:
        if nutrition.item.name == form.name.data:
            stock.nutrition = nutrition
            stock.save()
            return redirect(url_for('stock.stock_info',
                            stock_id=stock.id))

    item = models.Item(name=form.name.data,
                       description=form.description.data,
                       tags=ltags,
                       created_date=datetime.datetime.now(),
                       updated_date=datetime.datetime.now())
    item.save()
    
    allergen = models.Allergen()
    facts = models.NutritionFact()
    new_nutrition = models.Nutrition(item=item,
                                     allergen=allergen,
                                     facts=facts,
                                     created_date=datetime.datetime.now(),
                                     updated_date=datetime.datetime.now())
    new_nutrition.save()
    
    stock.nutrition = new_nutrition
    stock.save()

    return redirect(url_for('stock.stock_info',
                            stock_id=stock.id))


@module.route('/increase_stock/<stock_id>', methods=['GET', 'POST'])
@login_required
def increase_stock(stock_id):
    user = models.User.objects.get(id=current_user._get_current_object().id)
    stock = models.Stock.objects().get(id=stock_id) 
    form = IncreaseStockForm()

    if not user:
        return redirect(url_for('user.initial_user'))

    if not form.validate_on_submit():
        return render_template('stock/increase_stock.html',
                               form=form,
                               stock=stock,
                               user=user)
    
    stock.volume += form.volume.data
    stock.save()
    
    return redirect(url_for('stock.stock'))


@module.route('/edit_stock/<stock_id>', methods=['GET', 'POST'])
@login_required
def edit_stock(stock_id):
    form = StockForm()
    user = models.User.objects.get(id=current_user._get_current_object().id)
    stock = models.Stock.objects.get(id=stock_id)

    if not user:
        return redirect(url_for('user.initial_user'))

    if not form.validate_on_submit():
        form.name.data = stock.name
        form.description.data = stock.description
        form.tags.data = ','.join(stock.tags)
        form.volume.data = stock.volume
        form.amount_type.data = stock.amount_type
        form.stock_type.data = stock.stock_type
        return render_template('stock/edit_stock.html',
                               form=form,
                               stock=stock,
                               user=user)
    
    new_srt = form.tags.data.strip()
    if new_srt.endswith(','):
        new_srt = new_srt[:-1]
    if new_srt.startswith(','):
        new_srt = new_srt[1:]
    ltags = [tag for tag in  new_srt.split(',') if tag != '']

    print(form.name.data)
    stock.name = form.name.data
    stock.description = form.description.data
    stock.tags = ltags
    stock.volume = form.volume.data
    stock.amount_type = form.amount_type.data
    stock.stock_type = form.stock_type.data
    stock.update_date = datetime.datetime.now()
    stock.save()

    return redirect(url_for('stock.stock_info',
                            stock_id=stock.id))



@module.route('/delete_stock/<stock_id>', methods=['GET', 'POST'])
def delete_stock(stock_id):
    stock = models.Stock.objects.get(id=stock_id)
    stock.delete()
    return redirect(url_for('stock.stock'))

bhagsahan/templates/stock/add_stock.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
        <div class="row">
          <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
            <div class="card white z-depth-3">
              <div class="card-content">
                <span class="card-title">Add More Stock</span>
                <form enctype="multipart/form-data" method="POST">
                {{form.csrf_token}}
                  <div class="row" style="margin-top: 2%">
                    <div class="input-field col s12 m12">
                      {{form.name}}
                      {{form.name.label}}
                    </div>
                    <div class="input-field col s12 m12">
                      {{form.description}}
                      {{form.description.label}}
                    </div>
                    <div class="input-field col s12 m12">
                      {{form.tags}}
                      {{form.tags.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.volume}}
                      {{form.volume.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.amount_type}}
                      {{form.amount_type.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.stock_type}}
                      {{form.stock_type.label}}
                    </div>
                  </div>
                  <div class="row">
                    <button class="green darken-4 btn btn-primary col s12 m6 l6 xl6 offset-m3 offset-l3 offset-xl3" type="submit">Submit</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
    </div>
      
{% endblock %}

bhagsahan/templates/stock/edit_stock.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
        <div class="row">
          <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
            <div class="card white z-depth-3">
              <div class="card-content">
                <span class="card-title">Edit Stock</span>
                <div class="col s12">
                    <a href="#modalDelete" class="right modal-trigger red lighten-1 btn" style="border-radius: 5px"><i class="material-icons">delete</i>Delete</a>
                </div>
                <form enctype="multipart/form-data" method="POST">
                {{form.csrf_token}}
                {{ form.errors }}
                  <div class="row" style="margin-top: 2%">
                    <div class="input-field col s12 m12">
                      {{form.name}}
                      {{form.name.label}}
                    </div>
                    <div class="input-field col s12 m12">
                      {{form.description}}
                      {{form.description.label}}
                    </div>
                    <div class="input-field col s12 m12">
                      {{form.tags}}
                      {{form.tags.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.volume}}
                      {{form.volume.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.amount_type}}
                      {{form.amount_type.label}}
                    </div>
                    <div class="input-field col s6 m6">
                      {{form.stock_type}}
                      {{form.stock_type.label}}
                    </div>
                  <div class="row">
                    <button class="green darken-4 btn btn-primary col s12 m6 l6 xl6 offset-m3 offset-l3 offset-xl3" type="submit">Submit</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
    </div>
    <div id="modalDelete" class="modal">
        <div class="modal-content">
          <div class="row center">
            <h5>Do you want to delete this information?</h5>
          </div>
          <div class="row center">
            <a class="btn light-blue darken-4 z-depth-0" href="{{ url_for('stock.delete_stock', stock_id=stock.id) }}">Yes</a>
            <a class="btn red darken-2 z-depth-0 modal-close" >No</a>
          </div>
        </div>
    </div>
      
{% endblock %}

bhagsahan/templates/stock/increase_stock.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
        <div class="row">
          <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
            <div class="card white z-depth-3">
              <div class="card-content">
                <span class="card-title">Increase this stock</span>
                <form enctype="multipart/form-data" method="POST">
                {{form.csrf_token}}
                  <div class="row" style="margin-top: 2%">
                    <div class="input-field col s12 m12">
                        You have {{ stock.volume }} {{ stock.amount_type }} of {{ stock.name }} in stock
                    </div>
                    <div class="input-field col s6 m6">
                        {{form.volume}}
                        {{form.volume.label}}
                    </div>
                    <div class="input-field col s6 m6">
                        {{ stock.amount_type }}
                    </div>
                  <div class="row">
                    <button class="green darken-4 btn btn-primary col s12 m6 l6 xl6 offset-m3 offset-l3 offset-xl3" type="submit">Submit</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
    </div>
      
{% endblock %}

bhagsahan/templates/stock/stock.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
        <span style="font-size: 1.64rem">Stock</span>
        <div class="divider"></div>
        <div class="card grey lighten-5" style="margin-top: 3%">
            <div class="container">
                <div class="row">
                    <table>
                        <thead>
                            <tr>
                                <th>Stock Name</th>
                                <th>Amount</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for stock in stocks %}
                            <tr>
                                <td>{{ stock.name }}</td>
                                <td>{{ stock.volume }} {{ stock.amount_type }}</td>
                                {% if stock.volume > 0 %}
                                    <td>Have in stock</td>
                                {% else %}
                                    <td>Out of stock</td>
                                {% endif %}
                                <td>
                                    <a class="btn-floating btn-small red lighten-1" href="{{ url_for('stock.increase_stock', stock_id=stock.id) }}"><i class="material-icons">add</i></a>
                                    <a class="btn-floating btn-small" style="background-color:#1E3B4C" href="{{ url_for('stock.stock_info', stock_id=stock.id) }}"><i class="material-icons">description</i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>  
        </div>
    </div>
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large red" href="{{ url_for('stock.add_stock') }}" >
          <i class="large material-icons">add_to_photos</i>
        </a>
    </div>
{% endblock %}

bhagsahan/templates/stock/stock_info.html
{% extends "/base/base_layout.html" %}
{% block content %}
<div class="container" style="margin-top: 5%">
  <div class="row">
    <div class="col s12 m12 l10 xl10 offset-l1 offset-xl1 ">
      <div class="card white z-depth-3">
        <div class="card-content">
          <span class="card-title">Stock Infomation</span>
            <div class="row" style="margin-top: 2%">
              <div class="col s12 m12 l7 xl8" style="margin-top: 1rem">
                Name : 
                {{ stock.name }}
              </div>
              <div class="col s12 m12 l7 xl8" style="margin-top: 1rem">
                Description : 
                {{ stock.description }}
              </div>
              <div class="col s12 m12 l7 xl8" style="margin-top: 1rem">
                Tags :
                {% for tag in stock.tags %}
                  {{ tag }}
                {% endfor %}
              </div>
              <div class="col s12 m12 l7 xl8" style="margin-top: 1rem">
                Amount : 
                {{ stock.volume }}  {{ stock.amount_type }}
              </div>
              <div class="col s12 m12 l7 xl8" style="margin-top: 1rem">
                Status : 
                {% if stock.volume > 0  %}
                  Have in Stock
                {% else %}
                  Out of Stock
                {% endif %}
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="fixed-action-btn">
  <a class="btn-floating btn-large red lighten-1" href="{{ url_for('stock.edit_stock', stock_id= stock.id) }}" >
    <i class="large material-icons red lighten-1">mode_edit</i>
  </a>
</div>
{% endblock %}