bhagsahan/views/suggestion.py
from flask import (Blueprint, 
                   request, 
                   render_template, 
                   redirect, 
                   url_for,
                   current_app,
                   Flask)
from mongoengine.queryset.visitor import Q
from .. import models
from bhagsahan.forms import SelectMoreFoodForm, NumberOfPelpleForm
# from the-warehourse import oauth2
# from the-warehourse.forms import LoginForm, RegisterForm
# from flask_user import (UserMixin, 
#                         login_required, 
#                         current_user,
#                         user_manager)
# from flask_login import login_user
from werkzeug.security import generate_password_hash, check_password_hash
from flask import Flask, redirect, url_for, session, request, jsonify
from flask_login import logout_user, current_user, login_required

import datetime


module = Blueprint('suggestion', __name__, url_prefix='/')


def update_food_status():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    recipes = models.Recipe.objects()
    stocks = models.Stock.objects() 

    suggested_recipes = []
    un_suggested_recipes = []

    for recipe in recipes:
        check_list = []
        recipe_status_list = []
        recipe_allergen_list = []
        for recipe_ingredient in recipe.ingredients:
            check = False
            recipe_status = False
            recipe_allergen = False
            for stock in stocks:
                if recipe_ingredient.name == stock.name:
                    check = True
                    if stock.volume >= recipe_ingredient.volume:
                        recipe_status = True
                    if stock.nutrition and user.allergen and stock.nutrition.allergen:
                        if (stock.nutrition.allergen.eggs and user.allergen.eggs) or \
                           (stock.nutrition.allergen.fish and user.allergen.fish) or \
                           (stock.nutrition.allergen.gluten and user.allergen.gluten) or \
                           (stock.nutrition.allergen.milk and user.allergen.milk) or \
                           (stock.nutrition.allergen.peanuts and user.allergen.peanuts) or \
                           (stock.nutrition.allergen.shellfish and user.allergen.shellfish) or \
                           (stock.nutrition.allergen.soybeans and user.allergen.soybeans) or \
                           (stock.nutrition.allergen.tree_nuts and user.allergen.tree_nuts) or \
                           (stock.nutrition.allergen.wheat and user.allergen.wheat):
                            recipe_allergen = True

            check_list.append(check)
            recipe_status_list.append(recipe_status)
            recipe_allergen_list.append(recipe_allergen)

        recipe.ingredient_status = True           
        for i in check_list:
            if i == False:
                recipe.ingredient_status = False

        recipe.status = True
        for i in recipe_status_list:
            if i == False:
                recipe.status = False

        recipe.allergen_status = False
        for i in recipe_allergen_list:
            if i == True:
                recipe.allergen_status = True         

        recipe.save()


@module.route('/suggest', methods=['GET', 'POST'])
@login_required
def suggest_menu():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    recipes = models.Recipe.objects()
    stocks = models.Stock.objects() 
    if not user:
        return redirect(url_for('user.initial_user'))

    update_food_status()

    return render_template('suggestion/suggest.html',
                            user=user,
                            recipes=recipes)
        

@module.route('/suggest_a_la_carte', methods=['GET', 'POST'])
@login_required
def suggest_menu_a_la_carte():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    update_food_status()
    recipes = models.Recipe.objects()
    stocks = models.Stock.objects() 
    if not user:
        return redirect(url_for('user.initial_user'))

    return render_template('suggestion/suggest_a_la_carte.html',
                            user=user,
                            recipes=recipes)
        

@module.route('/suggest_side_dish', methods=['GET', 'POST'])
@login_required
def suggest_menu_side_dish():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    update_food_status()
    recipes = models.Recipe.objects(side_dish=True)
    stocks = models.Stock.objects() 
    if not user:
        return redirect(url_for('user.initial_user'))

    return render_template('suggestion/suggest_side_dish.html',
                            user=user,
                            recipes=recipes)


@module.route('/rec_suggest', methods=['GET', 'POST'])
@login_required
def rec_suggest():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    update_food_status()
    recipes = models.Recipe.objects()
    stocks = models.Stock.objects() 
    form = SelectMoreFoodForm()
    if not user:
        return redirect(url_for('user.initial_user'))

    return render_template('suggestion/rec_suggest.html',
                            user=user,
                            recipes=recipes)
    

@module.route('/rec_suggest_a_la_carte', methods=['GET', 'POST'])
@login_required
def rec_suggest_a_la_carte():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    update_food_status()
    recipes = models.Recipe.objects()
    stocks = models.Stock.objects() 
    form = SelectMoreFoodForm()
    if not user:
        return redirect(url_for('user.initial_user'))
    
    return render_template('suggestion/rec_suggest_a_la_carte.html',
                            user=user,
                            recipes=recipes)
    

@module.route('/rec_suggest_side_dish', methods=['GET', 'POST'])
@login_required
def rec_suggest_side_dish():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    update_food_status()
    recipes = models.Recipe.objects(side_dish=True)
    stocks = models.Stock.objects() 
    form = SelectMoreFoodForm()
    if not user:
        return redirect(url_for('user.initial_user'))

    return render_template('suggestion/rec_suggest_side_dish.html',
                            user=user,
                            recipes=recipes)


@module.route('/order_suggest', methods=['GET', 'POST'])
@login_required
def order_suggest():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    update_food_status()
    recipes = models.Recipe.objects()
    stocks = models.Stock.objects() 
    form = SelectMoreFoodForm()
    if not user:
        return redirect(url_for('user.initial_user'))
    
    return render_template('suggestion/order_suggest.html',
                            user=user,
                            recipes=recipes)


@module.route('/order_suggest_a_la_carte', methods=['GET', 'POST'])
@login_required
def order_suggest_a_la_carte():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    update_food_status()
    recipes = models.Recipe.objects.order_by('calories')
    stocks = models.Stock.objects() 
    form = SelectMoreFoodForm()
    if not user:
        return redirect(url_for('user.initial_user'))

    return render_template('suggestion/order_suggest_a_la_carte.html',
                            user=user,
                            recipes=recipes)


@module.route('/order_suggest_side_dish', methods=['GET', 'POST'])
@login_required
def order_suggest_side_dish():
    user = models.User.objects.get(id=current_user._get_current_object().id)
    update_food_status()
    recipes = models.Recipe.objects(side_dish=True).order_by('calories')
    stocks = models.Stock.objects() 
    form = SelectMoreFoodForm()
    if not user:
        return redirect(url_for('user.initial_user'))

    return render_template('suggestion/order_suggest_side_dish.html',
                            user=user,
                            recipes=recipes)


@module.route('/suggest_info/<recipe_id>')
@login_required
def suggest_info(recipe_id):
    user = models.User.objects.get(id=current_user._get_current_object().id)
    recipe = models.Recipe.objects().get(id=recipe_id)
    stocks = models.Stock.objects()
    list_stock_name=[]
    for stock in stocks:
        list_stock_name.append(stock.name)

    if not user:
        return redirect(url_for('user.initial_user'))
    return render_template('suggestion/suggest_info.html',
                           recipe=recipe,
                           stocks=stocks,
                           list_stock_name=list_stock_name,
                           user=user)


@module.route('/food_selected/<int:cal>/<recipe_id>', methods=['GET', 'POST'])
@login_required
def food_selected(cal, recipe_id):
    user = models.User.objects.get(id=current_user._get_current_object().id)
    recipe = models.Recipe.objects().get(id=recipe_id)
    stocks = models.Stock.objects()
    if not user:
        return redirect(url_for('user.initial_user'))

    user.cal_limit -= cal
    user.cal_limit_per_week -= cal
    user.calories_in += cal
    if user.cal_limit < 0:
        user.cal_limit = 0
    if user.cal_limit_per_week < 0:
        user.cal_limit_per_week = 0
        
    for ingredient in recipe.ingredients:
        for stock in stocks:
            if ingredient.name == stock.name:
                stock.volume -= ingredient.volume
                if stock.volume < 0:
                    stock.volume = 0
                stock.save()    
                break
        for stock in stocks:
            if ingredient.name == stock.name and stock.nutrition.food_group:
                if stock.nutrition.food_group.protein:
                    user.food_group.protein = True
                if stock.nutrition.food_group.carbohydrate:
                    user.food_group.carbohydrate = True

bhagsahan/templates/suggestion/order_suggest.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
        <span style="font-size: 1.64rem">Order by calories</span>
        <ul class="pagination">
            <li class="active"><a href="#!">All Menu</a></li>
            <li class="waves-effect"><a href="{{ url_for('suggestion.suggest_menu_a_la_carte') }}">A la carte</a></li>
            <li class="waves-effect"><a href="{{ url_for('suggestion.suggest_menu_side_dish') }}">Side Dish</a></li>
        </ul>
        <div class="divider"></div>
        <ul class="pagination">
            <li class="waves-effect"><a href="{{ url_for('suggestion.suggest_menu') }}">All</a></li>
            <li class="active"><a href="#!">Order by calories</a></li>
            <li class="waves-effect"><a href="{{ url_for('suggestion.rec_suggest') }}">Recommend</a></li>
        </ul>
        <div class="row" style="margin-top: 3%">
            <div class="col s12 m12">
                <nav class="white">
                <div class="nav-wrapper">
                    <form action="{{ url_for('suggestion.suggestion_search_result') }}" method="GET">
                    <div class="input-field">
                        <input id="search" type="search" name="search" placeholder="Find your Menu" class="validate search-field">
                        <label class="label-icon" for="search"><i class="material-icons black-text">search</i></label>
                        <input type="submit" class="hide">
                        <i class="material-icons close-btn">close</i>
                    </div>
                    </form>
                </div>
                </nav>
            </div>
        </div>
        <div class="row" style="margin-top: 3%">
        {% for recipe in recipes %}
                {% if recipe.ingredient_status %}
                    <div class="col s12 m6">
                        <div class="card">
                        <div class="card-image">
                              {% if recipe.image %}
                                <img class="activator" width="300" height="310" src="{{ url_for('recipe.recipe_image', recipe_id=recipe.id, file_name=recipe.image.filename) }}" >
                                <span class="card-title">{{ recipe.name }}</span>
                              {% else %}
                                <img class="activator" width="300" height="310" src="{{ url_for('static', filename='images/undraw_Hamburger_8ge6.png') }}" >
                                <span class="card-title black-text">{{ recipe.name }}</span>
                              {% endif %}
                            <a href="{{ url_for('suggestion.suggest_info', recipe_id=recipe.id) }}" class="btn-floating halfway-fab waves-effect waves-light red lighten-1"><i class="material-icons">chevron_right</i></a>
                        </div>
                        <div class="card-content">
                            {% if recipe.calories <= 600 and recipe.calories <= user.cal_limit %}
                                <a class="chip teal lighten-2"><p>Calories Recommended</p></a>
                            {% else %}
                                <a class="chip red lighten-1"><p>Calories Unrecommended</p></a>
                            {% endif %}
                            {% if recipe.status %}
                                <a class="chip teal lighten-2"><p>Can cook</p></a>
                            {% else %}
                            <a class="chip red lighten-1"><p>Can not cook</p></a>
                            {% endif %}
                            {% if recipe.allergen_status %}
                                <a class="chip red lighten-1"><p>Have allergens</p></a>
                            {% endif %}
                            <p><br></p>
                            <p>Calories : {{ recipe.calories }} / {{ recipe.unit }}</p>
                        </div>
                        </div>
                    </div>
                {% else %}
                    <div class="col s12 m6">
                        <div class="card">
                        <div class="card-image">
                              {% if recipe.image %}
                                <img class="activator" width="300" height="310" src="{{ url_for('recipe.recipe_image', recipe_id=recipe.id, file_name=recipe.image.filename) }}" style="-webkit-filter: grayscale(100%); filter: grayscale(100%);" >
                                <span class="card-title">{{ recipe.name }}</span>
                              {% else %}
                                <img class="activator" width="300" height="310" src="{{ url_for('static', filename='images/undraw_Hamburger_8ge6.png') }}" style="-webkit-filter: grayscale(100%); filter: grayscale(100%);">
                                <span class="card-title black-text">{{ recipe.name }}</span>
                              {% endif %}
                            <a href="{{ url_for('suggestion.suggest_info', recipe_id=recipe.id) }}" class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">chevron_right</i></a>
                        </div>
                        <div class="card-content">
                            <a class="chip"><p>No some ingredient in stock</p></a>
                            <p><br></p>
                            <p>Calories : {{ recipe.calories }} / {{ recipe.unit }}</p>
                        </div>
                        </div>
                    </div>
                
            {% endif %}
        {% endfor %}
        </div>
    </div>
{% endblock %}

bhagsahan/templates/suggestion/order_suggest_a_la_carte.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
        <span style="font-size: 1.64rem">Order by calories</span>
        <ul class="pagination">
            <li class="waves-effect"><a href="{{ url_for('suggestion.suggest_menu') }}">All Menu</a></li>
            <li class="active"><a href="#!">A la carte</a></li>
            <li class="waves-effect"><a href="{{ url_for('suggestion.suggest_menu_side_dish') }}">Side Dish</a></li>
        </ul>
        <div class="divider"></div>
        <ul class="pagination">
            <li class="waves-effect"><a href="{{ url_for('suggestion.suggest_menu_a_la_carte') }}">All</a></li>
            <li class="active"><a href="#!">Order by calories</a></li>
            <li class="waves-effect"><a href="{{ url_for('suggestion.rec_suggest_a_la_carte') }}">Recommend</a></li>
        </ul>
        <div class="row" style="margin-top: 3%">
            <div class="col s12 m12">
                <nav class="white">
                <div class="nav-wrapper">
                    <form action="{{ url_for('suggestion.suggestion_search_result') }}" method="GET">
                    <div class="input-field">
                        <input id="search" type="search" name="search" placeholder="Find your Menu" class="validate search-field">
                        <label class="label-icon" for="search"><i class="material-icons black-text">search</i></label>
                        <input type="submit" class="hide">
                        <i class="material-icons close-btn">close</i>
                    </div>
                    </form>
                </div>
                </nav>
            </div>
        </div>
        <div class="row" style="margin-top: 3%">
        {% for recipe in recipes %}
            {% if not recipe.side_dish %}
                {% if recipe.ingredient_status %}
                <div class="col s12 m6">
                    <div class="card">
                    <div class="card-image">
                        {% if recipe.image %}
                            <img class="activator" width="300" height="310" src="{{ url_for('recipe.recipe_image', recipe_id=recipe.id, file_name=recipe.image.filename) }}" >
                            <span class="card-title">{{ recipe.name }}</span>
                        {% else %}
                            <img class="activator" width="300" height="310" src="{{ url_for('static', filename='images/undraw_Hamburger_8ge6.png') }}" >
                            <span class="card-title black-text">{{ recipe.name }}</span>
                        {% endif %}
                        <a href="{{ url_for('suggestion.suggest_info', recipe_id=recipe.id) }}" class="btn-floating halfway-fab waves-effect waves-light red lighten-1"><i class="material-icons">chevron_right</i></a>
                    </div>
                    <div class="card-content">
                        {% if recipe.calories <= 600 and recipe.calories <= user.cal_limit %}
                            <a class="chip teal lighten-2"><p>Calories Recommended</p></a>
                        {% else %}
                            <a class="chip red lighten-1"><p>Calories Unrecommended</p></a>
                        {% endif %}
                        {% if recipe.status %}
                            <a class="chip teal lighten-2"><p>Can cook</p></a>
                        {% else %}
                        <a class="chip red lighten-1"><p>Can not cook</p></a>
                        {% endif %}
                        {% if recipe.allergen_status %}
                            <a class="chip red lighten-1"><p>Have allergens</p></a>
                        {% endif %}
                        <p><br></p>
                        <p>Calories : {{ recipe.calories }} / {{ recipe.unit }}</p>
                    </div>
                    </div>
                </div>
                {% else %}
                    <div class="col s12 m6">
                        <div class="card">
                        <div class="card-image">
                            {% if recipe.image %}
                                <img class="activator" width="300" height="310" src="{{ url_for('recipe.recipe_image', recipe_id=recipe.id, file_name=recipe.image.filename) }}" style="-webkit-filter: grayscale(100%); filter: grayscale(100%);" >
                                <span class="card-title">{{ recipe.name }}</span>
                            {% else %}
                                <img class="activator" width="300" height="310" src="{{ url_for('static', filename='images/undraw_Hamburger_8ge6.png') }}" style="-webkit-filter: grayscale(100%); filter: grayscale(100%);">
                                <span class="card-title black-text">{{ recipe.name }}</span>
                            {% endif %}
                            <a href="{{ url_for('suggestion.suggest_info', recipe_id=recipe.id) }}" class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">chevron_right</i></a>
                        </div>
                        <div class="card-content">
                            <a class="chip"><p>No some ingredient in stock</p></a>
                            <p><br></p>
                            <p>Calories : {{ recipe.calories }} / {{ recipe.unit }}</p>
                        </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        {% endfor %}
        </div>
    </div>
{% endblock %}

bhagsahan/templates/suggestion/order_suggest_side_dish.html
{% extends "/base/base_layout.html" %}
{% block content %}
    <div class="container" style="margin-top: 5%">
        <span style="font-size: 1.64rem">Order by calories</span>
        <ul class="pagination">
            <li class="waves-effect"><a href="{{ url_for('suggestion.suggest_menu') }}">All Menu</a></li>
            <li class="waves-effect"><a href="{{ url_for('suggestion.suggest_menu_a_la_carte') }}">A la carte</a></li>
            <li class="active"><a href="#!">Side Dish</a></li>
        </ul>
        <div class="divider"></div>
        <ul class="pagination">
            <li class="waves-effect"><a href="{{ url_for('suggestion.suggest_menu_side_dish') }}">All</a></li>
            <li class="active"><a href="#!">Order by calories</a></li>
            <li class="waves-effect"><a href="{{ url_for('suggestion.rec_suggest_side_dish') }}">Recommend</a></li>
        </ul>
        <div class="row" style="margin-top: 3%">
            <div class="col s12 m12">
                <nav class="white">
                <div class="nav-wrapper">
                    <form action="{{ url_for('suggestion.suggestion_search_result') }}" method="GET">
                    <div class="input-field">
                        <input id="search" type="search" name="search" placeholder="Find your Menu" class="validate search-field">
                        <label class="label-icon" for="search"><i class="material-icons black-text">search</i></label>
                        <input type="submit" class="hide">
                        <i class="material-icons close-btn">close</i>
                    </div>
                    </form>
                </div>
                </nav>
            </div>
        </div>
        <div class="row" style="margin-top: 3%">
        {% for recipe in recipes %}
                {% if recipe.ingredient_status %}
                    <div class="col s12 m6">
                        <div class="card">
                        <div class="card-image">
                              {% if recipe.image %}
                                <img class="activator" width="300" height="310" src="{{ url_for('recipe.recipe_image', recipe_id=recipe.id, file_name=recipe.image.filename) }}" >
                                <span class="card-title">{{ recipe.name }}</span>
                              {% else %}
                                <img class="activator" width="300" height="310" src="{{ url_for('static', filename='images/undraw_Hamburger_8ge6.png') }}" >
                                <span class="card-title black-text">{{ recipe.name }}</span>
                              {% endif %}
                            <a href="{{ url_for('suggestion.suggest_info', recipe_id=recipe.id) }}" class="btn-floating halfway-fab waves-effect waves-light red lighten-1"><i class="material-icons">chevron_right</i></a>
                        </div>
                        <div class="card-content">
                            {% if recipe.calories <= 600 and recipe.calories <= user.cal_limit %}
                                <a class="chip teal lighten-2"><p>Calories Recommended</p></a>
                            {% else %}
                                <a class="chip red lighten-1"><p>Calories Unrecommended</p></a>
                            {% endif %}
                            {% if recipe.status %}
                                <a class="chip teal lighten-2"><p>Can cook</p></a>
                            {% else %}
                            <a class="chip red lighten-1"><p>Can not cook</p></a>
                            {% endif %}
                            {% if recipe.allergen_status %}
                                <a class="chip red lighten-1"><p>Have allergens</p></a>
                            {% endif %}
                            <p><br></p>
                            <p>Calories : {{ recipe.calories }} / {{ recipe.unit }}</p>
                        </div>
                        </div>
                    </div>
                {% else %}
                    <div class="col s12 m6">
                        <div class="card">
                        <div class="card-image">
                              {% if recipe.image %}
                                <img class="activator" width="300" height="310" src="{{ url_for('recipe.recipe_image', recipe_id=recipe.id, file_name=recipe.image.filename) }}" style="-webkit-filter: grayscale(100%); filter: grayscale(100%);" >
                                <span class="card-title">{{ recipe.name }}</span>
                              {% else %}
                                <img class="activator" width="300" height="310" src="{{ url_for('static', filename='images/undraw_Hamburger_8ge6.png') }}" style="-webkit-filter: grayscale(100%); filter: grayscale(100%);">
                                <span class="card-title black-text">{{ recipe.name }}</span>
                              {% endif %}
                            <a href="{{ url_for('suggestion.suggest_info', recipe_id=recipe.id) }}" class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">chevron_right</i></a>
                        </div>
                        <div class="card-content">
                            <a class="chip"><p>No some ingredient in stock</p></a>
                            <p><br></p>
                            <p>Calories : {{ recipe.calories }} / {{ recipe.unit }}</p>
                        </div>
                        </div>
                    </div>
            {% endif %}
        {% endfor %}
        </div>
    </div>
{% endblock %}

bhagsahan/templates/suggestion/rec_suggest.html
{% extends "/base/base_layout.html" %}

{% block content %}
    <div class="container" style="margin-top: 5%">
        <span style="font-size: 1.64rem">Menu Recommended</span>
        <ul class="pagination">
            <li class="active"><a href="#!">All Menu</a></li>
            <li class="waves-effect"><a href="{{ url_for('suggestion.suggest_menu_a_la_carte') }}">A la carte</a></li>
            <li class="waves-effect"><a href="{{ url_for('suggestion.suggest_menu_side_dish') }}">Side Dish</a></li>
        </ul>
        <div class="divider"></div>
        <ul class="pagination">
            <li class="waves-effect"><a href="{{ url_for('suggestion.suggest_menu') }}">All</a></li>
            <li class="waves-effect"><a href="{{ url_for('suggestion.order_suggest') }}">Order by calories</a></li>
            <li class="active"><a href="#!">Recommend</a></li>
        </ul>
        <div class="row" style="margin-top: 3%">
            <div class="col s12 m12">
                <nav class="white">
                <div class="nav-wrapper">
                    <form action="{{ url_for('suggestion.suggestion_search_result') }}" method="GET">
                    <div class="input-field">
                        <input id="search" type="search" name="search" placeholder="Find your Menu" class="validate search-field">
                        <label class="label-icon" for="search"><i class="material-icons black-text">search</i></label>
                        <input type="submit" class="hide">
                        <i class="material-icons close-btn">close</i>
                    </div>
                    </form>
                </div>
                </nav>
            </div>
        </div>
        <div class="row" style="margin-top: 3%">
        {% for recipe in recipes %}
                {% if recipe.ingredient_status and recipe.status and recipe.calories <= 600 and recipe.calories <= user.cal_limit and not recipe.allergen_status %}
                    <div class="col s12 m6">
                        <div class="card">
                            <div class="card-image">
                                  {% if recipe.image %}
                                    <img class="activator" width="300" height="310" src="{{ url_for('recipe.recipe_image', recipe_id=recipe.id, file_name=recipe.image.filename) }}" >
                                    <span class="card-title">{{ recipe.name }}</span>
                                  {% else %}
                                    <img class="activator" width="300" height="310" src="{{ url_for('static', filename='images/undraw_Hamburger_8ge6.png') }}" >
                                    <span class="card-title black-text">{{ recipe.name }}</span>
                                  {% endif %}
                                <a href="{{ url_for('suggestion.suggest_info', recipe_id=recipe.id) }}" class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">chevron_right</i></a>
                            </div>
                            <div class="card-content">
                                {% if recipe.calories <= 600 and recipe.calories <= user.cal_limit %}
                                    <a class="chip teal lighten-2"><p>Calories Recommended</p></a>
                                {% else %}
                                    <a class="chip red lighten-1"><p>Calories Unrecommended</p></a>
                                {% endif %}
                                {% if recipe.status %}
                                    <a class="chip teal lighten-2"><p>Can cook</p></a>
                                {% else %}
                                <a class="chip red lighten-1"><p>Can not cook</p></a>
                                {% endif %}
                                {% if recipe.allergen_status %}
                                    <a class="chip red lighten-1"><p>Have allergens</p></a>
                                {% endif %}
                                <p><br></p>
                                <p>Calories : {{ recipe.calories }} / {{ recipe.unit }}</p>
                            </div>
                        </div>
                    </div>
                {% endif %}
        {% endfor %}
        </div>
    </div>
{% endblock %}